//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc1project
{
    using System;
    using System.Collections.Generic;
    
    public partial class apply
    {
        public int apply_id { get; set; }
        public int job_id { get; set; }
        public int candidate_id { get; set; }
        public System.DateTime apply_date { get; set; }
        public string resume { get; set; }
        public string status { get; set; }
    }
}
