//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc1project
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidate1
    {
        public int candidate_id { get; set; }
        public string candidate_name { get; set; }
        public int age { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string gender { get; set; }
        public string qualification { get; set; }
        public string skills { get; set; }
        public int experience { get; set; }
    }
}
