//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc1project
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        public int job_id { get; set; }
        public int company_id { get; set; }
        public string title { get; set; }
        public string skills { get; set; }
        public string location { get; set; }
        public string salary { get; set; }
        public string experience { get; set; }
        public string job_status { get; set; }
        public System.DateTime last_date { get; set; }
    }
}
