//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc1project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class mvcprojectEntities : DbContext
    {
        public mvcprojectEntities()
            : base("name=mvcprojectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<apply> applies { get; set; }
        public virtual DbSet<candidate1> candidate1 { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<job> jobs { get; set; }
        public virtual DbSet<login> logins { get; set; }
    
        public virtual int sp_appinsert(Nullable<int> jid, Nullable<int> uid, Nullable<System.DateTime> adate, string cv, string astatus)
        {
            var jidParameter = jid.HasValue ?
                new ObjectParameter("jid", jid) :
                new ObjectParameter("jid", typeof(int));
    
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var adateParameter = adate.HasValue ?
                new ObjectParameter("adate", adate) :
                new ObjectParameter("adate", typeof(System.DateTime));
    
            var cvParameter = cv != null ?
                new ObjectParameter("cv", cv) :
                new ObjectParameter("cv", typeof(string));
    
            var astatusParameter = astatus != null ?
                new ObjectParameter("astatus", astatus) :
                new ObjectParameter("astatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_appinsert", jidParameter, uidParameter, adateParameter, cvParameter, astatusParameter);
        }
    
        public virtual int sp_candidatereg(Nullable<int> cid, string cna, Nullable<int> ag, string addr, string ph, string em, string gnd, string quali, string sk, Nullable<int> exp)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var cnaParameter = cna != null ?
                new ObjectParameter("cna", cna) :
                new ObjectParameter("cna", typeof(string));
    
            var agParameter = ag.HasValue ?
                new ObjectParameter("ag", ag) :
                new ObjectParameter("ag", typeof(int));
    
            var addrParameter = addr != null ?
                new ObjectParameter("addr", addr) :
                new ObjectParameter("addr", typeof(string));
    
            var phParameter = ph != null ?
                new ObjectParameter("ph", ph) :
                new ObjectParameter("ph", typeof(string));
    
            var emParameter = em != null ?
                new ObjectParameter("em", em) :
                new ObjectParameter("em", typeof(string));
    
            var gndParameter = gnd != null ?
                new ObjectParameter("gnd", gnd) :
                new ObjectParameter("gnd", typeof(string));
    
            var qualiParameter = quali != null ?
                new ObjectParameter("quali", quali) :
                new ObjectParameter("quali", typeof(string));
    
            var skParameter = sk != null ?
                new ObjectParameter("sk", sk) :
                new ObjectParameter("sk", typeof(string));
    
            var expParameter = exp.HasValue ?
                new ObjectParameter("exp", exp) :
                new ObjectParameter("exp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_candidatereg", cidParameter, cnaParameter, agParameter, addrParameter, phParameter, emParameter, gndParameter, qualiParameter, skParameter, expParameter);
        }
    
        public virtual int sp_cmpnyreg(Nullable<int> cmpid, string cmpna, string cmpaddr, string cmpphone, string cmpweb, string cmpdes)
        {
            var cmpidParameter = cmpid.HasValue ?
                new ObjectParameter("cmpid", cmpid) :
                new ObjectParameter("cmpid", typeof(int));
    
            var cmpnaParameter = cmpna != null ?
                new ObjectParameter("cmpna", cmpna) :
                new ObjectParameter("cmpna", typeof(string));
    
            var cmpaddrParameter = cmpaddr != null ?
                new ObjectParameter("cmpaddr", cmpaddr) :
                new ObjectParameter("cmpaddr", typeof(string));
    
            var cmpphoneParameter = cmpphone != null ?
                new ObjectParameter("cmpphone", cmpphone) :
                new ObjectParameter("cmpphone", typeof(string));
    
            var cmpwebParameter = cmpweb != null ?
                new ObjectParameter("cmpweb", cmpweb) :
                new ObjectParameter("cmpweb", typeof(string));
    
            var cmpdesParameter = cmpdes != null ?
                new ObjectParameter("cmpdes", cmpdes) :
                new ObjectParameter("cmpdes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_cmpnyreg", cmpidParameter, cmpnaParameter, cmpaddrParameter, cmpphoneParameter, cmpwebParameter, cmpdesParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_isapplied(Nullable<int> uid, Nullable<int> jid)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var jidParameter = jid.HasValue ?
                new ObjectParameter("jid", jid) :
                new ObjectParameter("jid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_isapplied", uidParameter, jidParameter);
        }
    
        public virtual int sp_job(Nullable<int> cid, string title, string sk, string loc, string sal, string exp, string jbstatus, Nullable<System.DateTime> lstdate)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var skParameter = sk != null ?
                new ObjectParameter("sk", sk) :
                new ObjectParameter("sk", typeof(string));
    
            var locParameter = loc != null ?
                new ObjectParameter("loc", loc) :
                new ObjectParameter("loc", typeof(string));
    
            var salParameter = sal != null ?
                new ObjectParameter("sal", sal) :
                new ObjectParameter("sal", typeof(string));
    
            var expParameter = exp != null ?
                new ObjectParameter("exp", exp) :
                new ObjectParameter("exp", typeof(string));
    
            var jbstatusParameter = jbstatus != null ?
                new ObjectParameter("jbstatus", jbstatus) :
                new ObjectParameter("jbstatus", typeof(string));
    
            var lstdateParameter = lstdate.HasValue ?
                new ObjectParameter("lstdate", lstdate) :
                new ObjectParameter("lstdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_job", cidParameter, titleParameter, skParameter, locParameter, salParameter, expParameter, jbstatusParameter, lstdateParameter);
        }
    
        public virtual int sp_jobsearches(string qry)
        {
            var qryParameter = qry != null ?
                new ObjectParameter("qry", qry) :
                new ObjectParameter("qry", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_jobsearches", qryParameter);
        }
    
        public virtual ObjectResult<sp_jobview_Result> sp_jobview(Nullable<int> jid, Nullable<int> cid)
        {
            var jidParameter = jid.HasValue ?
                new ObjectParameter("jid", jid) :
                new ObjectParameter("jid", typeof(int));
    
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_jobview_Result>("sp_jobview", jidParameter, cidParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_logincountid(string una, string pwd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_logincountid", unaParameter, pwdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_loginreg(string una, string pwd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_loginreg", unaParameter, pwdParameter);
        }
    
        public virtual int sp_loginsert(Nullable<int> rid, string una, string pw, string lgtype)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwParameter = pw != null ?
                new ObjectParameter("pw", pw) :
                new ObjectParameter("pw", typeof(string));
    
            var lgtypeParameter = lgtype != null ?
                new ObjectParameter("lgtype", lgtype) :
                new ObjectParameter("lgtype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_loginsert", ridParameter, unaParameter, pwParameter, lgtypeParameter);
        }
    
        public virtual ObjectResult<string> sp_logtype(string una, string pwd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_logtype", unaParameter, pwdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_maxidlogin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_maxidlogin");
        }
    }
}
